"""empty message

Revision ID: 4dc47c160e26
Revises: 
Create Date: 2018-11-23 17:00:49.187464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc47c160e26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultima_alteracao', sa.DateTime(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultima_alteracao', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultima_alteracao', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultima_alteracao', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('data_de_emissao', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemdopedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_de_criacao', sa.DateTime(), nullable=False),
    sa.Column('ultima_alteracao', sa.DateTime(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('preco_de_tabela', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.Column('preco_liquido', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.Column('total', sa.Numeric(precision=21, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresa.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedido.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemdopedido')
    op.drop_table('pedido')
    op.drop_table('produto')
    op.drop_table('cliente')
    op.drop_table('empresa')
    # ### end Alembic commands ###
